### ISSUE TITLE
ImportError: cannot import name ellipkm1? whta's package for ellipkml?

### ISSUE THREAD

**Issue by andyyuan78** [jamong/music-rnn#2]
envy@ub1404:~/os_pri/github/music-rnn/rnn_lstm_jzs1_eng$ python train_piano.py
Using Theano backend.
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
/home/envy/.local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Traceback (most recent call last):
  File "train_piano.py", line 11, in <module>
    from model_util import *
  File "/home/envy/os_pri/github/music-rnn/rnn_lstm_jzs1_eng/model_util.py", line 3, in <module>
    import scipy.io as sio
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/**init**.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/**init**.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/**init**.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/usr/local/lib/python2.7/dist-packages/scipy/special/**init**.py", line 629, in <module>
    from .basic import *
  File "/usr/local/lib/python2.7/dist-packages/scipy/special/basic.py", line 14, in <module>
    from ._ufuncs import (ellipkm1, mathieu_a, mathieu_b, iv, jv, gamma, psi, zeta,
ImportError: cannot import name ellipkm1
envy@ub1404:~/os_pri/github/music-rnn/rnn_lstm_jzs1_eng$

**Comment by dade-ai** [comment]
It seems ellipkm1 is a module of scipy and the other possible reason is outdated numpy version.
How about to try upgrade numpy or/and reinstall scipy?

**Comment by dade-ai** [comment]
For your information. the followings are installed versions in my computer. and there's no trouble to run..
$ pip freeze | grep scipy
scipy==0.17.0
$ pip freeze | grep numpy
numpy==1.10.4
